# Generated by Django 3.1 on 2024-05-23 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=1000)),
                ('version', models.IntegerField(default=0)),
                ('area_name', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'In-active'), (2, 'Processing'), (3, 'Conflicted'), (4, 'Error during processing')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'In-active'), (2, 'Processing'), (3, 'Conflicted'), (4, 'Error during processing')], default=1)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('version', models.IntegerField(default=0)),
                ('added_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('weightage', models.IntegerField(default=1)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'In-active'), (2, 'Processing'), (3, 'Conflicted'), (4, 'Error during processing')], default=1)),
                ('version', models.IntegerField(default=0)),
                ('added_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('description', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'In-active'), (2, 'Processing'), (3, 'Conflicted'), (4, 'Error during processing')], default=1)),
                ('version', models.IntegerField(default=0)),
                ('added_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_id', to='nobroker.countries')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_type_available', models.IntegerField(choices=[(0, 'Single Room'), (1, 'Double Sharing'), (2, 'Triple Sharing'), (3, 'Dormitory')])),
                ('rent_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_tenants', models.CharField(max_length=255)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('food_facility', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('gate_closing_time', models.TimeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nobroker.areas')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nobroker.cities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buildup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_tenants', models.CharField(max_length=255)),
                ('furnisher', models.IntegerField(choices=[(0, 'Unfurnished'), (1, 'Semi-furnished'), (2, 'Fully furnished')])),
                ('apartment_type', models.IntegerField(choices=[(0, 'Studio'), (1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4 BHK')])),
                ('ready_to_move', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nobroker.areas')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nobroker.cities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flatmates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buildup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furnishing', models.IntegerField(choices=[(0, 'Unfurnished'), (1, 'Semi-furnished'), (2, 'Fully furnished')])),
                ('apartment_type', models.IntegerField(choices=[(0, 'Studio'), (1, '1 BHK'), (2, '2 BHK'), (3, '3 BHK'), (4, '4 BHK')])),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('available_from', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nobroker.areas')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nobroker.cities')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_id', to='nobroker.states'),
        ),
        migrations.AddField(
            model_name='areas',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hops', to='nobroker.cities'),
        ),
    ]
